services:
  # Banco de Dados PostgreSQL
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zapcash-network

  # Redis para Filas e Cache
  redis:
    image: redis:6-alpine
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASS}"]
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - zapcash-network

  # Backend (API)
  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
      - redis
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      REDIS_URI: redis://:${REDIS_PASS}@redis:6379
      REDIS_OPT_LIMITER_MAX: 1
      BACKEND_URL: https://${BACKEND_DOMAIN}
      FRONTEND_URL: https://${FRONTEND_DOMAIN}
      VERIFY_TOKEN: ${VERIFY_TOKEN}
      FACEBOOK_APP_ID: ${FACEBOOK_APP_ID}
      FACEBOOK_APP_SECRET: ${FACEBOOK_APP_SECRET}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      PROXY_PORT: 8080
      PORT: 8080
    volumes:
      - ./backend/public:/app/public
    networks:
      - zapcash-network

  # Frontend (React)
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_URL: https://${BACKEND_DOMAIN}
        REACT_APP_FACEBOOK_APP_ID: ${FACEBOOK_APP_ID}
    restart: always
    depends_on:
      - backend
    networks:
      - zapcash-network

  # Nginx Proxy Reverso (Gateway)
  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - zapcash-network

  # Certbot para SSL Gratuito (Opcional, mas recomendado)
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; done;'"

volumes:
  postgres_data:
  redis_data:

networks:
  zapcash-network:
    driver: bridge
